apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server-ingress
  namespace: microservice-api-gitops-demo
  annotations:
    kubernetes.io/ingress.class: traefik
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    # Use TLS passthrough instead of termination to preserve the TLS connection to the backend
    traefik.ingress.kubernetes.io/router.tls.passthrough: "true"
    argocd.argoproj.io/tracking-id: micro-service:networking.k8s.io/Ingress:microservice-api-gitops-demo/argocd-server-ingress
spec:
  rules:
  - host: argocd.0xkatana.site
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-demo-server
            port:
              number: 443
  tls:
  - hosts:
    - argocd.0xkatana.site
    secretName: argocd-tls