apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-microservice-api-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "traefik"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    traefik.ingress.kubernetes.io/router.tls: "true"
spec:
  tls:
  - hosts:
    - api-kustomize-k8s.0xkatana.site
    secretName: k8s-micro-tls
  rules:
  - host: api-kustomize-k8s.0xkatana.site
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: demo-microservice-api-svc
            port:
              number: 3000