apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- secrets.yml
- deployment.yml
- svc.yml
- ingress.yml
#- certificate.yml
#- external-dns.yml
- cluster-issuer.yml

images:
  - name: ghcr.io/h3xkatana/k8s-microservices-demo-api
    newTag: "main-6dfe6c7"